# Site Settings
title: Craig Wang's Resume
url: 'http://craigwangstat.github.io'
baseurl: '/CraigWangStat.github.io' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Craig Wang
tagline: Statistician
pic: id.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A well-versed statistician who is passionate about problem solving.'

#sidebar links
email: craigwang247♡gmail.com
phone: 
website: craigwangstat.github.io #do not add http://
linkedin: craigwang247
github: CraigWangUZH
twitter: '@CraigWangUZH'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-91822230-3

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

theme: jekyll-theme-cayman